server:
  port: 8080
  servlet:
    context-path: /api

spring:
  application:
    name: child-adoption-system

  datasource:
    url: jdbc:h2:mem:testdb
    username: sa
    password: password
    driver-class-name: org.h2.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.H2Dialect
        format_sql: true

  servlet:
    multipart:
      enabled: true
      max-file-size: 10MB
      max-request-size: 10MB

  jackson:
    serialization:
      FAIL_ON_EMPTY_BEANS: false  # ✅ This is what you asked for

logging:
  level:
    com.adoption: DEBUG
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics

file:
  upload:
    dir: uploads/
    max-size: 10MB
